services:
    - postgresql

addons:
    postgresql: '9.6'

before_script:
  - cp config/database.travis.yml config/database.yml

language: ruby

dist: bionic

rvm:
  — 2.6.3

script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec