services:
    - postgresql
    
addons:
  postgresql: "10.10"
  apt:
    packages:
    - postgresql-10.10
    - postgresql-client-10.10
env:
  global:
  - PGPORT=5433

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

language: ruby
dist: bionic

rvm:
  — 2.6.3

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec