services:
    - postgresql

addons:
    postgresql: '10.10'

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

language: ruby
dist: trusty

rvm:
  — 2.6.3

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec